sudo: required
dist: trusty
language: cpp
os:
  - linux
compiler:
  - gcc
install:
  - travis_retry sudo apt-get -qq -y update
  - travis_retry sudo apt-get -qq -y install autoconf automake autopoint bash bison bzip2 cmake flex gettext git g++ gperf intltool libffi-dev libgdk-pixbuf2.0-dev libtool libltdl-dev libssl-dev libxml-parser-perl make openssl p7zip-full patch perl pkg-config python ruby scons sed unzip wget xz-utils g++-multilib libc6-dev-i386 libboost-program-options1.55-dev
before_script:
  - ./toolchain.sh
script:
  - ./build.sh
